name: CI

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Code
        uses: actions/checkout@v3
      - name: Check diff between gofmt and code
        run: diff <(gofmt -d .) <(echo -n)
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Code
        uses: actions/checkout@v3
      - name: Run tests
        run: go test -v -race ./...
  
  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Code
        uses: actions/checkout@v3
      - name: Go vet
        run: go vet -x ./...
